name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      #- name: Deploy
      #  run: aws s3 sync ./src/.vuepress/dist s3://${{ secrets.BUCKET_NAME }}
  tag:
    needs: deploy
    name: 'Create new tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "mateusmalaquais@outlook.com"
      - name: Bump version
        run: npx standard-version
      - name: Push tag
        run: git push --follow-tags origin main -f
